### ISSUE TITLE
Is the example correct?

### ISSUE THREAD

**Issue by ldelelis** [ui/django-thumbnails#70]
In the provided example:

```python
import thumbnails

class Food(models.Model):
    image = thumbnails.Field()


food = Food.objects.latest('id')
food.image.thumbnails.all()
food.image.thumbnails.small  # Generates "small" sized thumbnail
food.image.thumbnails.large  # Generates "large" sized thumbnail
food.image.thumbnails.small.url  # Returns "small" sized thumbnail URL
```

The model field is declared as `thumbnails.Fields()`. However, after trying both with a django shell and with the code itself, all cases fail with error "AttributeError: 'module' object has no attribute 'Field'". Moreover, the package's `__init__.py` file only provides a VERSION constant, so there should be no way `Field` could be called directly from the module.

Am I misinterpreting the example? Or is there something that's not being said here? Running Python 2.7, Django 1.11

**Comment by selwin** [comment]
Sorry about that, I have updated the README to reflect the correct import path.
